//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
